import{a as L,S as b,i as l}from"./assets/vendor-DnBR8w-b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const v="49323961-66159e96cf1899f53bae32983",E="https://pixabay.com/api/";async function m(t,o=1,i=15){try{return(await L.get(E,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const g=document.querySelector(".gallery");function y(t){g.innerHTML=t.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:a,comments:h,downloads:p})=>`
      <li class="gallery-item">
        <a href="${s}" class="gallery-link">
          <img src="${i}" alt="${e}" class="gallery-image" />
        </a>
        <div class="info">
          <p>❤️ ${r}</p>
          <p>👀 ${a}</p>
          <p>💬 ${h}</p>
          <p>⬇️ ${p}</p>
        </div>
      </li>`).join(""),new b(".gallery a").refresh()}function S(){g.innerHTML=""}const w=document.querySelector(".form"),q=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");let c="",n=1;const f=15;w.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements["search-text"].value.trim(),!c){l.error({title:"Error",message:"Please enter a search query!"});return}n=1,S(),u.classList.add("hidden"),d.classList.add("visible");try{const{hits:o,totalHits:i}=await m(c,n,f);if(o.length===0){l.warning({title:"Oops!",message:"No images found. Try again!"});return}y(o),u.classList.toggle("hidden",i<=f)}catch{l.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{d.classList.remove("visible")}});u.addEventListener("click",async()=>{n+=1,d.classList.add("visible");try{const{hits:t,totalHits:o}=await m(c,n,f);y(t),n*f>=o&&(u.classList.add("hidden"),l.info({message:"We're sorry, but you've reached the end of search results."})),$()}catch{l.error({title:"Error",message:"Failed to load more images."})}finally{d.classList.remove("visible")}});function $(){const{height:t}=q.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
